/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as ConductorRouteImport } from './routes/conductor'
import { Route as HomeRouteImport } from './routes/home'
import { Route as PinkCardRouteImport } from './routes/pink-card'
import { Route as PinkCardApplyRouteImport } from './routes/pink-card-apply'
import { Route as TripsRouteImport } from './routes/trips'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductorRoute = ConductorRouteImport.update({
  id: '/conductor',
  path: '/conductor',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PinkCardRoute = PinkCardRouteImport.update({
  id: '/pink-card',
  path: '/pink-card',
  getParentRoute: () => rootRouteImport,
} as any)
const PinkCardApplyRoute = PinkCardApplyRouteImport.update({
  id: '/pink-card-apply',
  path: '/pink-card-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/conductor': typeof ConductorRoute
  '/home': typeof HomeRoute
  '/pink-card': typeof PinkCardRoute
  '/pink-card-apply': typeof PinkCardApplyRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/conductor': typeof ConductorRoute
  '/home': typeof HomeRoute
  '/pink-card': typeof PinkCardRoute
  '/pink-card-apply': typeof PinkCardApplyRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/conductor': typeof ConductorRoute
  '/home': typeof HomeRoute
  '/pink-card': typeof PinkCardRoute
  '/pink-card-apply': typeof PinkCardApplyRoute
  '/trips': typeof TripsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/conductor'
    | '/home'
    | '/pink-card'
    | '/pink-card-apply'
    | '/trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/conductor'
    | '/home'
    | '/pink-card'
    | '/pink-card-apply'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/conductor'
    | '/home'
    | '/pink-card'
    | '/pink-card-apply'
    | '/trips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  ConductorRoute: typeof ConductorRoute
  HomeRoute: typeof HomeRoute
  PinkCardRoute: typeof PinkCardRoute
  PinkCardApplyRoute: typeof PinkCardApplyRoute
  TripsRoute: typeof TripsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conductor': {
      id: '/conductor'
      path: '/conductor'
      fullPath: '/conductor'
      preLoaderRoute: typeof ConductorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pink-card': {
      id: '/pink-card'
      path: '/pink-card'
      fullPath: '/pink-card'
      preLoaderRoute: typeof PinkCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pink-card-apply': {
      id: '/pink-card-apply'
      path: '/pink-card-apply'
      fullPath: '/pink-card-apply'
      preLoaderRoute: typeof PinkCardApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  ConductorRoute: ConductorRoute,
  HomeRoute: HomeRoute,
  PinkCardRoute: PinkCardRoute,
  PinkCardApplyRoute: PinkCardApplyRoute,
  TripsRoute: TripsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
